Math Magicians: tests
sahlminkok/MathMagicians pull request #7
Opened 2023-06-23 14:35 UTC by sahlminkok

### In this Pull Request we:
- Set up React Testing Library.
- Write unit tests for the files operate.js and calculate.js using Jest.
- Create unit tests for all React components:
- Run the full tests suite using Jest. All tests have passed.

2023-06-23 18:22 UTC, HAMMAS-SALEEM requested changes
# Required Changes :recycle:
![Ukhv](https://user-images.githubusercontent.com/93039359/247195854-e274f284-2e3a-423b-8939-7e4efb638ee0.gif)

## Hey @porag-m06, @sahlminkok :wave:

## Highlights :1st_place_medal:

✔️ Descriptive PR Title
✔️ Descriptive PR Summary
✔️ Following Gitflow
✔️ Following some requirements
✔️ Great work on adding the tests for components 👍

Good job on implementing some of the requirements, there are some issues that you still need to work on to go to the next project but you are almost there! :blush:

# Optional

_All the changes with optional tags are not crucial enough to prevent you from getting the approval. Still, we highly recommend to students that they should take these changes into consideration._

Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

---------------------------------------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-23 18:22 UTC, HAMMAS-SALEEM commented on public/manifest.json
>  {
![image](https://github.com/sahlminkok/MathMagicians/assets/93039359/ac3dd058-ea91-49c4-8b23-7caa7004b117)

- [ ] It would be nice if you make your all tests green ✔️ because right only one of them is broken 😨 Kindly make your test verify that your app functionality is working as expected 👍

2023-06-23 18:22 UTC, HAMMAS-SALEEM commented on public/manifest.json
>      {
**[OPTIONAL]**

- [ ] It would be nice if you make your own logo of your name and put that in the readme file at the top to present yourself as a brand in the job market or tech industry to catch the recruiters' eyes 👍

2023-06-23 19:01 UTC, porag-m06 commented on public/manifest.json
>  {
Hi, @HAMMAS-SALEEM, thanks for the feedback. However, though there is a console error warning but the test actually passed. Please have a look at the screen shot below, 
![image](https://github.com/sahlminkok/MathMagicians/assets/15729467/9d087174-369f-4cff-bd5f-7054c6a0e8f2)

It would really help if you could shed some light on that it that could be a BLOCKER please. Thanks

2023-06-24 05:13 UTC, divinecharlotte approved these changes
# Hello @sahlminkok       😃 🥳 🎉 🎈 

Great Job 😄 👏 You've done it. Your project is complete!  There is nothing else to say  👍🏻 ✅ 
### To Highlight 💯


- Descriptive pr👍 
- Good implementation of the required changes 👍 
 




## Congratulations! 🎉 

<img src="https://media3.giphy.com/media/3KC2jD2QcBOSc/giphy.gif"/>

Cheers, and Happy coding!👏👏👏


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-24 05:17 UTC, merged